name=PIO_LSM6DS3
version=0.1.0
author=Arduino
maintainer=Lucas Riepe <riepelucas@gmail.com>
sentence=Allows you to read the accelerometer, gyroscope, and temperature values from the LSM6DS3 IMU on your ESP32 baord.
paragraph=
category=Sensors
url=
architectures=*
includes=PIO_LSM6DS3.hpp
